version: 2.1 # Latest Version Available

jobs:
  build:
    machine:
      image: ubuntu-2004:current
    resource_class: large
      
    steps: 
      - run: |
          echo "Initial Packages"
          cd ~
          sudo apt install git aria2 -y
      - run: |
          echo "Necessary Packages"
          git clone https://gitlab.com/OrangeFox/misc/scripts && cd scripts && sudo bash setup/android_build_env.sh
      - run: |
          echo "Sync Sources"
          mkdir ~/OrangeFox && cd ~/OrangeFox
          git clone https://gitlab.com/OrangeFox/sync.git
          cd ~/OrangeFox/sync
          ./orangefox_sync.sh --branch 12.1 --path ~/fox_12.1
      - run: |
          echo "Clone Device Tree"
          cd ~/fox_12.1
          git clone https://github.com/cd-Spidey/custom_recovery_tree_xiaomi_cannong ./device/xiaomi/cannong
      - run: |
          echo "Build OrangeFox"
          cd ~/fox_12.1
          source ./build/envsetup.sh
          export ALLOW_MISSING_DEPENDENCIES=true
          export FOX_USE_TWRP_RECOVERY_IMAGE_BUILDER=1
          export LC_ALL="C"
          lunch twrp_cannong-eng && mka adbd recovery.img
          
