version: 2.1 # Latest Version Available

jobs:
  build:
    machine:
      image: ubuntu-2004:current
    resource_class: large
      
    steps: 
      - run:
          name: Initial Packages
          command: |
            cd ~
            sudo apt install git aria2 -y
      - run:
          name: Necessary Packages
          command: |
            git clone https://gitlab.com/OrangeFox/misc/scripts
            cd scripts
            sudo bash setup/android_build_env.sh
      - run:
          name: Sync Sources
          command: |
            mkdir ~/OrangeFox && cd ~/OrangeFox
            git clone https://github.com/cd-Spidey/OrangeFox-Action-Builder ./Sync
            chmod a+x ~/OrangeFox/Sync/sync/orangefox_sync.sh
            cd ~/OrangeFox/Sync/sync
            (yes || true) | ./orangefox_sync.sh --branch 12.1 --path ~/fox_12.1
      - run: 
          name: Build OrangeFox
          command: |
            cd ~/fox_12.1
            git clone https://github.com/cd-Spidey/custom_recovery_tree_xiaomi_cannong ./device/xiaomi/cannong
            source ./build/envsetup.sh
            export ALLOW_MISSING_DEPENDENCIES=true
            export FOX_USE_TWRP_RECOVERY_IMAGE_BUILDER=1
            export LC_ALL="C"
            lunch twrp_cannong-eng && mka adbd recovery.img

      - run:
          name: Creating Dummy Artifacts
          command: |
            echo "OrangeFox*.img" > ~/fox_12.1/out/target/product/cannong/OrangeFox*.img
            echo "OrangeFox*.zip" > ~/fox_12.1/out/target/product/cannong/OrangeFox*.zip
            mkdir /tmp/artifacts;
            echo "my artifact files in a dir" 

      - store_artifacts:
          path: |
            ~/fox_12.1/out/target/product/cannong/OrangeFox*.img
            ~/fox_12.1/out/target/product/cannong/OrangeFox*.zip
          destination: artifact-file
