version: 2.1 # Latest Version Available

jobs:
  build:
    machine:
      image: ubuntu-2004:current
    resource_class: large
      
    steps: 
      - run:
          name: Initial Packages
          command: |
            cd ~
            sudo apt install git aria2 -y
      - run:
          name: Necessary Packages
          command: |
            git clone https://gitlab.com/OrangeFox/misc/scripts
            cd scripts
            sudo bash setup/android_build_env.sh
      - run:
          name: Sync Sources
          command: |
            mkdir ~/OrangeFox && cd ~/OrangeFox
            git clone https://gitlab.com/OrangeFox/sync.git
            cd ~/OrangeFox/sync
            yes | ./orangefox_sync.sh --branch 12.1 --path ~/fox_12.1
      - run: 
          name: Build OrangeFox
          command: |
            cd ~/fox_12.1
            git clone https://github.com/cd-Spidey/custom_recovery_tree_xiaomi_cannong ./device/xiaomi/cannong
            source ./build/envsetup.sh
            export ALLOW_MISSING_DEPENDENCIES=true
            export FOX_USE_TWRP_RECOVERY_IMAGE_BUILDER=1
            export LC_ALL="C"
            lunch twrp_cannong-eng && mka adbd recovery.img
          
